//! `aerosync-proto` — Rust bindings for the AeroSync wire protocol.
//!
//! This crate is **purely generated**: every public type below is
//! produced by `prost-build` from `proto/aerosync/wire/v1.proto` at
//! build time. The schema is the canonical specification; this crate
//! is a typed view of it.
//!
//! See [RFC-002](https://github.com/TechVerseOdyssey/AeroSync/blob/main/docs/rfcs/RFC-002-receipt-protocol.md)
//! §6 for the wire format and stream layout, and
//! [RFC-003](https://github.com/TechVerseOdyssey/AeroSync/blob/main/docs/rfcs/RFC-003-metadata-envelope.md)
//! for the metadata envelope (lands in Week 4 of v0.2.0).
//!
//! ## Stability
//!
//! As long as the package is published with `version = "0.x"` we may
//! reshape the surface. Once we tag v0.2.0, `aerosync/1` is frozen and
//! field numbers in `wire/v1.proto` are immutable forever (only
//! additions allowed).
//!
//! ## ALPN
//!
//! [`VERSION`] is the canonical ALPN string negotiated on every QUIC
//! connection. Both endpoints in `aerosync` set this on their TLS
//! configuration; mismatched peers are rejected at handshake.

#![forbid(unsafe_code)]
// `missing_docs` is intentionally NOT enabled at the crate root: most
// of this crate's public surface is mechanically generated by
// `prost-build` and would never carry rustdoc. The hand-written items
// (`VERSION`, the `Timestamp` re-export) carry their own docs.

/// The canonical ALPN string for the AeroSync wire protocol.
///
/// Both QUIC client and server set this on their TLS configuration; a
/// peer that does not advertise it is rejected at handshake. See
/// RFC-002 §6.1.
pub const VERSION: &str = "aerosync/1";

// Pull in the prost-generated module. The path corresponds to the
// `package aerosync.wire.v1;` declaration at the top of `v1.proto`.
include!(concat!(env!("OUT_DIR"), "/aerosync.wire.v1.rs"));

// Re-export everything generated for the package at the crate root so
// callers can simply write `use aerosync_proto::Handshake;` rather
// than the longer `aerosync_proto::aerosync_wire_v1::Handshake`. The
// `include!` above already places the items at the crate root, but we
// re-export the well-known type alias for `Timestamp` for convenience
// (it lives in `prost_types`, which we depend on directly).

/// Re-export of `prost_types::Timestamp`, which is the Rust mapping for
/// the `google.protobuf.Timestamp` field on [`ReceiptFrame::at`].
pub use prost_types::Timestamp;

#[cfg(test)]
mod tests {
    use super::*;
    use prost::Message;

    #[test]
    fn version_string_matches_alpn() {
        assert_eq!(VERSION, "aerosync/1");
    }

    #[test]
    fn handshake_roundtrip() {
        let original = Handshake {
            protocol_version: "1".into(),
            sender_node_id: "node-a".into(),
            auth_proof: bytes::Bytes::from_static(b"deadbeef"),
            capabilities: 0b11,
        };
        let encoded = original.encode_to_vec();
        let decoded = Handshake::decode(encoded.as_slice()).expect("decode");
        assert_eq!(original, decoded);
    }

    #[test]
    fn transfer_start_roundtrip_without_metadata() {
        // A TransferStart with no metadata envelope is still a valid
        // RFC-002 frame. Legacy senders, smoke tests, and the
        // pre-Week-4 test suite all rely on this. After Week 4 the
        // engine always populates metadata, but the wire still
        // accepts a bare frame.
        let ts = TransferStart {
            receipt_id: "r-1".into(),
            file_name: "f.bin".into(),
            size_bytes: 42,
            sha256: "ab".repeat(32),
            metadata: None,
            chunk_size: 65_536,
        };
        let bytes = ts.encode_to_vec();
        let back = TransferStart::decode(bytes.as_slice()).expect("decode");
        assert_eq!(back.chunk_size, 65_536);
        assert_eq!(back.size_bytes, 42);
        assert!(back.metadata.is_none());
    }

    #[test]
    fn transfer_start_roundtrip_with_metadata() {
        // Round-trip a populated Metadata envelope through
        // TransferStart. Exercises the wire integration end-to-end at
        // the protobuf layer.
        let meta = Metadata {
            id: "r-1".into(),
            from_node: "alice".into(),
            to_node: "bob".into(),
            created_at: Some(prost_types::Timestamp {
                seconds: 1_700_000_000,
                nanos: 0,
            }),
            content_type: "application/octet-stream".into(),
            size_bytes: 42,
            sha256: "ab".repeat(32),
            file_name: "f.bin".into(),
            protocol: "quic".into(),
            trace_id: Some("run-7".into()),
            conversation_id: None,
            parent_file_ids: vec!["blob-a".into()],
            expires_at: None,
            lifecycle: Some(Lifecycle::Transient as i32),
            correlation_id: None,
            user_metadata: std::collections::HashMap::from([(
                "tenant".to_string(),
                "acme".to_string(),
            )]),
        };
        let ts = TransferStart {
            receipt_id: "r-1".into(),
            file_name: "f.bin".into(),
            size_bytes: 42,
            sha256: "ab".repeat(32),
            metadata: Some(meta.clone()),
            chunk_size: 65_536,
        };
        let bytes = ts.encode_to_vec();
        let back = TransferStart::decode(bytes.as_slice()).expect("decode");
        assert_eq!(back.metadata.as_ref(), Some(&meta));
        assert_eq!(back.metadata.unwrap().user_metadata["tenant"], "acme");
    }

    #[test]
    fn lifecycle_enum_default_is_unspecified() {
        assert_eq!(Lifecycle::default(), Lifecycle::Unspecified);
        assert_eq!(Lifecycle::Transient as i32, 1);
        assert_eq!(Lifecycle::Durable as i32, 2);
        assert_eq!(Lifecycle::Ephemeral as i32, 3);
    }

    #[test]
    fn receipt_frame_oneof_acked_smoke() {
        let frame = ReceiptFrame {
            receipt_id: "r-2".into(),
            body: Some(receipt_frame::Body::Acked(Acked {})),
            at: None,
        };
        let bytes = frame.encode_to_vec();
        let back = ReceiptFrame::decode(bytes.as_slice()).expect("decode");
        assert_eq!(back.receipt_id, "r-2");
        assert!(matches!(back.body, Some(receipt_frame::Body::Acked(_))));
    }

    #[test]
    fn error_code_default_is_unspecified() {
        // prost preserves protobuf enum identifier prefixes verbatim,
        // so `ERROR_UNSPECIFIED` becomes `ErrorUnspecified` in Rust.
        assert_eq!(ErrorCode::default(), ErrorCode::ErrorUnspecified);
    }

    #[test]
    fn state_enum_has_exactly_seven_variants() {
        // The parent execution plan calls for exactly 7 wire-level
        // states. INITIATED is the natural zero (default for a freshly
        // created Receipt) so we avoid a separate STATE_UNSPECIFIED.
        // If a contributor adds an 8th state without an accompanying
        // RFC, this test fires.
        let all = [
            State::Initiated,
            State::StreamOpened,
            State::DataTransferred,
            State::StreamClosed,
            State::Processing,
            State::Completed,
            State::Failed,
        ];
        assert_eq!(all.len(), 7);
        assert_eq!(State::Initiated as i32, 0);
        assert_eq!(State::Failed as i32, 6);
        // Default is INITIATED, not UNSPECIFIED.
        assert_eq!(State::default(), State::Initiated);
    }
}
